### ISSUE TITLE
[terraform-ibm-event-notifications] Add estimated-usage.yml to improve the calculated cost estimation

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-event-notifications#214]
We need to put in a yaml file like this : https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/blob/main/estimated-usage.yml to help with COS bucket estimations

**Comment by kierramarie** [comment]
Picked up issue. Starting to add usage yaml to project now.
