### ISSUE TITLE
[EN DA] COS module should not be called if using an existing bucket

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-event-notifications#219]
In the [DA](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/blob/main/solutions/standard/main.tf), I would expect a `count` around the `cos` module block for the use case where a user has passed an existing bucket with the `existing_cos_bucket_name` variable. If user is using an existing bucket, I see no reason why the COS module would need to be called.

**Comment by shemau** [comment]
1.6.2
