### ISSUE TITLE
COS/KMS resources should not be provisioned when existing EN CRN is supplied

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-event-notifications#265]
When the module is used with the existing Event Noitications instance CRN, the COS and KMS parameters should be ignored and the module should not try to provision the related resources (COS instances, buckets, S2S authorizations, KMS keys)

Currently it creates all of the above even though it cannot be connected to the existing EN instance.

### Affected modules

*

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
PR merged: https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/267
